background #2d353b
foreground #d3c6aa
selection_background #d3c6aa
selection_foreground #2d353b
cursor #d3c6aa
cursor_text_color #2d353b

color0 #475258
color1 #e67e80
color2 #a7c080
color3 #dbbc7f
color4 #7fbbb3
color5 #d699b6
color6 #83c092
color7 #d3c6aa
color8 #475258
color9 #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #83c092
color15 #d3c6aa

active_border_color #7fbbb3
inactive_border_color #475258
bell_border_color #dbbc7f

background_opacity 0.75
dynamic_background_opacity yes
window_padding_width 12
window_border_width 1px
draw_minimal_borders yes
hide_window_decorations titlebar-only
confirm_os_window_close 0
font_size 11.0
font_family Cascadia Code NF
bold_font auto
italic_font auto
bold_italic_font auto
