background #1f1f28
foreground #dcd7ba
selection_background #2d4f67
selection_foreground #c8c093
cursor #c8c093
cursor_text_color #1f1f28

color0 #090618
color1 #c34043
color2 #76946a
color3 #c0a36e
color4 #7e9cd8
color5 #957fb8
color6 #6a9589
color7 #c8c093
color8 #727169
color9 #e82424
color10 #98bb6c
color11 #e6c384
color12 #7fb4ca
color13 #938aa9
color14 #7aa89f
color15 #dcd7ba

active_border_color #7e9cd8
inactive_border_color #727169
bell_border_color #c0a36e

background_opacity 0.75
dynamic_background_opacity yes
window_padding_width 12
window_border_width 1px
draw_minimal_borders yes
hide_window_decorations titlebar-only
confirm_os_window_close 0
font_size 11.0
font_family Cascadia Code NF
bold_font auto
italic_font auto
bold_italic_font auto
